#!/bin/bash

# Function to check if Python 3.x is installed
check_python() {
    if command -v python3 &> /dev/null; then
        echo -e "\e[32mPython 3.x is installed:"
        python3 --version
        echo -e "\e[0m"
    elif command -v python &> /dev/null && python --version 2>&1 | grep -q "Python 3"; then
        echo -e "\e[32mPython 3.x is installed:"
        python --version
        echo -e "\e[0m"
    else
        echo -e "\e[31mPython is not installed. Downloading and installing Python 3.11.5...\e[0m"
        
        # Download Python 3.11.5
        wget https://www.python.org/ftp/python/3.11.5/Python-3.11.5.tar.xz
        
        # Extract the tar.xz file
        tar -xf Python-3.11.5.tar.xz
        
        # Navigate to the Python-3.11.5 directory
        cd Python-3.11.5
        
        # Configure and install Python
        ./configure
        make
        sudo make install
        
        # Return to the initial directory
        cd ..
        
        # Remove the downloaded file
        rm -rf Python-3.11.5 Python-3.11.5.tar.xz
        
        # Set an alias for python3
        echo -e "\e[32mPython 3.11.5 has been successfully installed."
        echo -e "Creating the 'python' alias...\e[0m"
        echo 'alias python=python3' >> ~/.bashrc
    fi
}

# Call the function to check Python
check_python

# Create a Python virtual environment
python3 -m venv venv

# Activate the virtual environment
echo -e "\e[32mActivating the virtual environment...\e[0m"
source venv/bin/activate

# Install dependencies from requirements.txt
echo -e "\e[32mInstalling dependencies from requirements.txt...\e[0m"
pip install --no-cache-dir -r requirements.txt

# Deactivate the virtual environment
echo -e "\e[32mDeactivating the virtual environment...\e[0m"
deactivate

echo -e "\e[32mThe development environment has been configured successfully."
echo -e "To activate the virtual environment and start coding, run:\e[0m"
echo -e "\e[36msource venv/bin/activate\e[0m"
