#!/bin/bash

docker run --name mon-conteneur-postgres \                                                                                                            ──(ven.,sept.15)─┘
  -p 5432:5432 \
  -v $(pwd)/userDb:/var/lib/postgresql/data \
  -d userdb