[package]
name = "user_service"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.4.11" # Specific version of Rocket 0.4
rocket_contrib = "0.4" # for Rocket 0.4
serde = { version = "1.0.187", features = ["derive"] }
serde_json = "1.0.106"
