name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Vous pouvez spécifier la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/nom_image:tag -f Dockerfile .
        docker push $DOCKER_USERNAME/nom_image:tag

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Créez un secret dans GitHub contenant votre nom d'utilisateur Docker Hub
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Créez un secret dans GitHub contenant votre mot de passe Docker Hub
